### ISSUE TITLE
while  Preview  .dwg   file  getting  Read  Only  Transaction  Error  in  alfresco

### ISSUE THREAD

**Issue by vikashsingh009** [verve111/alfresco_cad_support#2]
i  have  followed  the  steps  mentioned  on  doc ,But  when   i  am  trying to Preview .dwg file  .i  am   getting  Error  as 

 org.springframework.extensions.webscripts.WebScriptException: 03170002 Wrapped Exception (with status template): 03170189 Failed to execute script 'classpath*:alfresco/templates/webscripts/org/alfresco/repository/thumbnail/thumbnail.get.js': 03170188 Read-Write transaction started within read-only transaction

I  am  using  Alfresco   Community  Edition 5.2.0

**Comment by verve111** [comment]
It looks like your error is an Alfresco misconfiguration issue. And I guess it doesn't relate to my extension. Are you getting the same error without my extension installed?

**Comment by tusharkhanka** [comment]
i am facing the same issue can you please guide me how to fix it ?

**Comment by verve111** [comment]
Which version of Alfresco are you using?

**Comment by tusharkhanka** [comment]
i did a work around and now it is working okay with QCAD. But now my concern is how to reduce time for the document load .?

**Comment by verve111** [comment]
Please tell which workaround you used and which version of Alfresco (5.2?). Thanks. Are you asking why image conversion is slow?

**Comment by tusharkhanka** [comment]
yes, how can i make preview faster? and I was using the QCAD on a server so
i added the folowing command in -context.xml
./dwg2pdf -platform offscreen ...

**Comment by verve111** [comment]
Please tell which workaround you used and which version of Alfresco (5.2?).

**Comment by tusharkhanka** [comment]
my alfresco version is 5.2 july release and i found out .dxf preview doesn't loads up  
**ERROR [repo.action.AsynchronousActionExecutionQueueImpl] [defaultAsyncAction5] Failed to execute asynchronous action: Action[ id=3408ac66-62fd-41af-b192-185c0f7f3ca9, node=null ]: 07090131 Transformation of (Gear Sample-iss4.DXF) has not taken place because the declared mimetype (image/vnd.dxf) does not match the detected mimetype (text/plain)**

and i am using the trial version so it takes about 15 seconds to load , so if i use the professional version will it be any faster ?

and my work around was to do the transfomation on a server with no display . hence the command i user is **./dwg2pdf -platform offscreen ...** in my **-context.xml** file.

**Comment by verve111** [comment]
QCAD trial version adds extra 15 sec to each conversion. You can purchase a commercial version if you need a faster conversion.

**Comment by iris-sychel** [comment]
@vikashsingh005 You can **overwrite** _thumbnail.get.desc.xml_ file, there has a configuration for transaction, change it from **readonly** to **readwrite**, and then should be okay

@tusharkhanka This issue is because Alfresco auto-detect the file mimetype as text/plain, and there are 2 steps to solve it:
1. add  **transformer.strict.mimetype.check=false** to your alfresco-global.proeprties
2. under src/main/resource/alfresco/extension/mimetype, add mimetypes-custom-map.xml with content
```
<alfresco-config area="mimetype-map">

   <config evaluator="string-compare" condition="Mimetype Map">
      <mimetypes>

         <mimetype mimetype="image/vnd.dxf" display="DXF Mimetype">
            <extension>dxf</extension>
         </mimetype>

      </mimetypes>
   </config>

</alfresco-config>
```

Btw, all should be deployed in your platform jar
